/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkOnly, CacheFirst, NetworkFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

// eslint-disable-next-line no-undef
declare const self: ServiceWorkerGlobalScope;

// Precache all the assets generated by the build
precacheAndRoute(self.__WB_MANIFEST);

// Clean up outdated caches
cleanupOutdatedCaches();

// CRITICAL: Always fetch HTML from network to get latest paths/BASE_URL
// This prevents serving stale cached HTML with wrong asset paths
registerRoute(
  ({ request }) => request.mode === 'navigate',
  new NetworkFirst({
    cacheName: 'html-cache',
    networkTimeoutSeconds: 5,
  })
);

// Offline fallback for navigation requests (PWA cold launch with no network)
// Since HTML is not precached (runtime BASE_URL rewriting), provide a minimal
// app shell so users see a loading screen instead of a white screen.
import { setCatchHandler } from 'workbox-routing';

setCatchHandler(async ({ request }) => {
  if (request.mode === 'navigate') {
    return new Response(
      `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>MeshMonitor</title>
  <style>
    body { background: #1a1a1a; color: #e0e0e0; font-family: -apple-system, BlinkMacSystemFont, sans-serif;
           display: flex; align-items: center; justify-content: center; min-height: 100vh; margin: 0; }
    .offline { text-align: center; }
    .offline h1 { font-size: 1.5rem; margin-bottom: 0.5rem; }
    .offline p { color: #888; }
    .offline button { margin-top: 1rem; padding: 0.5rem 1.5rem; background: #3b82f6; color: white;
                      border: none; border-radius: 6px; font-size: 1rem; cursor: pointer; }
  </style>
</head>
<body>
  <div class="offline">
    <h1>MeshMonitor</h1>
    <p>Unable to connect. Check your network and try again.</p>
    <button onclick="location.reload()">Retry</button>
  </div>
</body>
</html>`,
      { headers: { 'Content-Type': 'text/html' } }
    );
  }
  return Response.error();
});

// Handle API routes (never cache)
// Use includes() instead of startsWith() to work with BASE_URL prefixes (e.g., /meshmonitor/api/)
registerRoute(({ url }) => url.pathname.includes('/api/'), new NetworkOnly());

// Handle map tiles from all supported providers (cache first).
// Use an exact-host allowlist (with optional subdomain match) instead of
// substring .includes() so that hostnames like
// "tile.openstreetmap.org.attacker.example" are NOT matched.
const MAP_TILE_HOSTS = new Set([
  'tile.openstreetmap.org',
  'basemaps.cartocdn.com',
  'tile.opentopomap.org',
  'server.arcgisonline.com',
]);
function isAllowedTileHost(hostname: string): boolean {
  if (MAP_TILE_HOSTS.has(hostname)) return true;
  for (const allowed of MAP_TILE_HOSTS) {
    if (hostname.endsWith('.' + allowed)) return true;
  }
  return false;
}
registerRoute(
  ({ url }) => isAllowedTileHost(url.hostname),
  new CacheFirst({
    cacheName: 'map-tiles',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 500,
        maxAgeSeconds: 60 * 60 * 24 * 30, // 30 days
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
);

// ==========================================
// PUSH NOTIFICATION HANDLERS
// ==========================================

// Navigation data interface for notification clicks
interface NotificationNavigationData {
  type: 'channel' | 'dm';
  channelId?: number;
  messageId?: string;
  senderNodeId?: string;
}

// Handle push events (background notifications)
self.addEventListener('push', event => {
  console.log('[Service Worker] Push received:', event);

  let notificationData = {
    title: 'MeshMonitor',
    body: 'You have a new notification',
    icon: '/logo.png',
    badge: '/logo.png',
    tag: undefined as string | undefined, // Will be set uniquely per notification
    data: undefined as NotificationNavigationData | undefined, // Navigation data for click handling
  };

  // Parse notification data from push payload
  if (event.data) {
    try {
      const data = event.data.json();
      notificationData = {
        title: data.title || notificationData.title,
        body: data.body || notificationData.body,
        icon: data.icon || notificationData.icon,
        badge: data.badge || notificationData.badge,
        tag: data.tag, // Use tag from payload, or undefined for unique notifications
        data: data.data, // Navigation data (channelId, messageId, senderNodeId)
      };
    } catch (error) {
      console.error('[Service Worker] Failed to parse push data:', error);
    }
  }

  // If no tag provided, use timestamp to ensure each notification is unique
  // This prevents macOS from replacing previous notifications
  const finalTag = notificationData.tag || `meshmonitor-${Date.now()}`;

  // CRITICAL for iOS: Use event.waitUntil() to keep service worker alive
  // iOS Safari requires this or the subscription gets cancelled after 3 notifications
  event.waitUntil(
    self.registration.showNotification(notificationData.title, {
      body: notificationData.body,
      icon: notificationData.icon,
      badge: notificationData.badge,
      tag: finalTag,
      data: notificationData.data, // Attach navigation data to notification
      requireInteraction: false, // Allow notifications to auto-dismiss
    } as NotificationOptions)
  );
});

// Handle notification clicks
self.addEventListener('notificationclick', event => {
  console.log('[Service Worker] Notification clicked:', event);

  // Get navigation data from the notification
  const navigationData = event.notification.data as NotificationNavigationData | undefined;

  if (navigationData) {
    console.log(
      '[Service Worker] Navigating to:',
      navigationData.type,
      navigationData.channelId ?? navigationData.senderNodeId
    );
  }

  event.notification.close();

  // Open or focus the MeshMonitor app and send navigation data
  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then(async clientList => {
      // Check if app is already open
      for (const client of clientList) {
        if (client.url.includes(self.registration.scope) && 'focus' in client) {
          // Focus the window
          await client.focus();
          // Send navigation data to the app if available
          if (navigationData) {
            client.postMessage({
              type: 'NOTIFICATION_CLICK',
              payload: navigationData,
            });
          }
          return;
        }
      }

      // If app is not open, open it with navigation data in URL hash
      if (self.clients.openWindow) {
        let url = self.registration.scope;
        if (navigationData) {
          // Encode navigation data in URL hash for the app to read on load
          const params = new URLSearchParams();
          params.set('notificationNav', JSON.stringify(navigationData));
          url = `${self.registration.scope}#${params.toString()}`;
        }
        return self.clients.openWindow(url);
      }
    })
  );
});

// Handle push subscription changes (e.g., subscription expired)
self.addEventListener('pushsubscriptionchange', event => {
  console.log('[Service Worker] Push subscription changed:', event);

  event.waitUntil(
    self.registration.pushManager
      .subscribe(event.oldSubscription?.options || { userVisibleOnly: true })
      .then(subscription => {
        console.log('[Service Worker] Re-subscribed:', subscription);

        const p256dh = subscription.getKey('p256dh');
        const auth = subscription.getKey('auth');

        if (!p256dh || !auth) {
          throw new Error('Missing subscription keys');
        }

        // Send new subscription to backend
        return fetch('/api/push/subscribe', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            subscription: {
              endpoint: subscription.endpoint,
              keys: {
                p256dh: arrayBufferToBase64(p256dh),
                auth: arrayBufferToBase64(auth),
              },
            },
          }),
        });
      })
      .catch(error => {
        console.error('[Service Worker] Re-subscription failed:', error);
      })
  );
});

// Helper function to convert ArrayBuffer to Base64
function arrayBufferToBase64(buffer: ArrayBuffer): string {
  const bytes = new Uint8Array(buffer);
  let binary = '';
  for (let i = 0; i < bytes.byteLength; i++) {
    binary += String.fromCharCode(bytes[i]);
  }
  return btoa(binary);
}

console.log('[Service Worker] MeshMonitor service worker with push notifications loaded');

// Skip waiting on install to activate new service worker immediately
self.addEventListener('install', event => {
  console.log('[Service Worker] Installing new service worker');
  event.waitUntil(self.skipWaiting());
});

// Claim all clients when activated
self.addEventListener('activate', event => {
  console.log('[Service Worker] Activating new service worker');
  event.waitUntil(
    self.clients.claim().then(() => {
      console.log('[Service Worker] Claimed all clients');
    })
  );
});
